Add a description about RLS to IVM documentation.
sraoss/pgsql-ivm pull request #81
Opened 2020-02-20 04:43 UTC by yugo-n

Github issue #71

2020-02-20 05:00 UTC, tatsuo-ishii requested changes

2020-02-20 05:00 UTC, tatsuo-ishii commented on doc/src/sgml/rules.sgml
> +    If some base table have row level security policy, rows that are not invisible
"base table" should be "base tables".
"invisible for" should be "invisible to".

2020-02-20 05:00 UTC, tatsuo-ishii commented on doc/src/sgml/rules.sgml
> +    are excluded also when views are incrementally maintained. However, if a new
"also" should "as well" or "too".

2020-02-20 05:00 UTC, tatsuo-ishii commented on doc/src/sgml/rules.sgml
> +    policy is defined  or policies are changed after materialized view definition,
There's extra space after "defined".
"after materialized view definition" should be "after the materialized view definition was created"

2020-02-20 05:00 UTC, tatsuo-ishii commented on doc/src/sgml/rules.sgml
> +    the new policy will not applied to the view contents. To apply the new policy,
"will not applied" should be "will not be applied".

2020-02-20 05:02 UTC, yugo-n commented
@tatsuo-ishii Thank you so much for your many pointing out my mistake!  I'll fix them.

2020-02-20 07:20 UTC, yugo-n commented
@tatsuo-ishii 

I fixed the typos. Also, I added a missing word as following:

"not invisible to the materialized view" 
 -> "not invisible to the materialized view's owner"

2020-02-21 03:14 UTC, tatsuo-ishii approved these changes

2020-02-21 04:22 UTC, yugo-n commented
Thanks for your review.  I'll merge it.

2020-02-21 04:23 UTC, merged